### ISSUE TITLE
环境部署问题咨询

### ISSUE THREAD

**Issue by ghost** [wrlu/SecIoT-Web#1]
您好，我使用的环境为：
Ubuntu 18.04
JDK8 Tomcat 9.0 mysql-server 
IDEA部署时，遇到问题较多。可否提供一份详细的部署资料？

**Comment by wrlu** [comment]
你好，因为最新的commit我尝试将环境切换为IDEA，但由于工作上的原因未经过充分测试。你可以考虑使用下面的版本，并使用Eclipse进行部署：
https://github.com/wrlu/SecIoT-Web/tree/e6a4eccbe98b0500207fde86da029c86c1aa663f

当然，较为推荐的办法是将项目打包为war文件，并直接使用Tomcat甚至是Docker进行部署。
